name: CI checks

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
      - name: cargo fetch
        run: cargo fetch
      - name: Build tests
        run: cargo build --all --verbose --all-features --tests
      - name: Run tests
        run: cargo test --all --verbose --all-features

  build:
    name: Build target ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
          targets: ${{ matrix.target }}
      - name: cargo fetch
        run: cargo fetch
      - name: Build for target
        run: cargo build --verbose --no-default-features --target ${{ matrix.target }} -p tlock_age

  bitrot:
    name: Bitrot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
      - name: cargo check
        run: cargo check --tests --examples --benches --all-features

  clippy:
    name: Clippy (1.87)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
          components: clippy
      - name: Clippy check
        run: cargo clippy --all-features --all-targets -- -D warnings

  doc-links:
    name: Intra-doc links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
      - name: cargo fetch
        run: cargo fetch

      # Ensure intra-documentation links all resolve correctly
      # Requires #![deny(intra_doc_link_resolution_failure)] in crates.
      - name: Check intra-doc links
        run: cargo doc --all --all-features --document-private-items

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.87
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
